Fix `ImportError: cannot import name 'CONFIG_DIR' from partially initialized module 'pylav.constants.config' (most likely due to a circular import) (.../pylav/constants/config/__init__.py)``